### Copyright 2025 Advanced Micro Devices, Inc.  All rights reserved.
### Licensed under the Apache License, Version 2.0 (the "License");
### you may not use this file except in compliance with the License.
### You may obtain a copy of the License at
###      http://www.apache.org/licenses/LICENSE-2.0
### Unless required by applicable law or agreed to in writing, software
### distributed under the License is distributed on an "AS IS" BASIS,
### WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
### See the License for the specific language governing permissions and
### limitations under the License.

FROM rocm/pytorch:rocm7.0_ubuntu24.04_py3.12_pytorch_release_2.8.0

WORKDIR /workspace

ARG GEOARCHES_COMMIT=90cc5fe

RUN git clone https://github.com/INRIA/geoarches.git && \
    cd geoarches && \
    git checkout ${GEOARCHES_COMMIT}

WORKDIR /workspace/geoarches

# Copy your patch into the container
COPY src/encode_dataset_input.patch ./ 

# Apply the patch before installing
RUN git apply encode_dataset_input.patch

# Install geoarches
RUN pip install -e . --no-deps

# Copy any additional source files if needed
COPY src/ ./

# Install ROCm-specific dependencies
RUN pip install -r ./requirements.rocm.txt